image:
  repository: wordpress
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 6.2.1-apache

imagePullSecrets: []
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: neuwied.shelterapp.spedat.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wordpress-test-backend-tls
      hosts:
        - neuwied.shelterapp.spedat.de
database:
  host: wordpress-db-mariadb.wordpress-db.svc
  port: 3306
  name: neuwied
  username: neuwied
  password: N4?%Q@6NaqmNZEWl1.6Q