<?php
/**
 * AnimalStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * shelterapp-backend API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AnimalStatus Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AnimalStatus
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'NEW';

    public const SEARCHING = 'SEARCHING';

    public const REQUEST_STOP = 'REQUEST_STOP';

    public const EMERGENCY = 'EMERGENCY';

    public const RESERVED = 'RESERVED';

    public const ADOPTED = 'ADOPTED';

    public const FINAL_CARE = 'FINAL_CARE';

    public const COURT_OF_GRACE = 'COURT_OF_GRACE';

    public const DECEASED = 'DECEASED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::SEARCHING,
            self::REQUEST_STOP,
            self::EMERGENCY,
            self::RESERVED,
            self::ADOPTED,
            self::FINAL_CARE,
            self::COURT_OF_GRACE,
            self::DECEASED
        ];
    }
}


