version: "3.8"

services:
  backend:
    image: counbellian7/shelterapp-backend:latest
    ports:
      - "8081:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: "postgresql://backend-db:5432/shelterapp"
      QUARKUS_DATASOURCE_USERNAME: shelterapp
      QUARKUS_DATASOURCE_PASSWORD: shelterapp
      QUARKUS_PROFILE: dev
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: "drop-and-create" # drop-and-create or update. Update is for when you want to keep your data
    depends_on:
      - backend-db
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: shelterapp
      WORDPRESS_DB_PASSWORD: shelterapp
      WORDPRESS_DB_NAME: shelterapp
      WORDPRESS_DEBUG: 1
    volumes:
#      - wordpress:/var/www/html
      - ./wp-plugin/shelterapp:/var/www/html/wp-content/plugins/shelterapp
      - ./wp-plugin/blocks/shelter-block-view:/var/www/html/wp-content/plugins/shelter-block-view
  wp-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: shelterapp
      MYSQL_USER: shelterapp
      MYSQL_PASSWORD: shelterapp
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
#    volumes:
#      - wp-db:/var/lib/mysql
  backend-db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: shelterapp
      POSTGRES_USER: shelterapp
      POSTGRES_PASSWORD: shelterapp
#    volumes:
#      - backend-db:/var/lib/postgresql/data
#volumes:
#  wordpress:
#  wp-db:
#  backend-dp: