apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shelterapp-backend.fullname" . }}
  labels:
    {{- include "shelterapp-backend.labels" . | nindent 4 }}
data:
  upload.ini: |
    upload_max_filesize = 100M
    post_max_size = 100M
