apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shelterapp-backend.fullname" . }}
  labels:
    {{- include "shelterapp-backend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "shelterapp-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shelterapp-backend.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.database.host }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.database.username | quote }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.database.name | quote }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: upload-config
              mountPath: /usr/local/etc/php/conf.d/

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "shelterapp-backend.fullname" . }}
        - name: upload-config
          configMap:
              name: {{ include "shelterapp-backend.fullname" . }}
              items:
                - key: upload.ini
                  path: upload.ini