apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shelterapp-backend.fullname" . }}
  labels:
    {{- include "shelterapp-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi