version: "3.1"

services:
  backend:
    image: bellian/shelterapp-backend:1.0-SNAPSHOT
    networks:
      - shelterapp-wp-plugin

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./shelterapp:/var/www/html/wp-content/plugins/shelterapp
      - ./blocks/shelter-block-view:/var/www/html/wp-content/plugins/shelter-block-view
    networks:
      - shelterapp-wp-plugin

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - shelterapp-wp-plugin
networks:
  shelterapp-wp-plugin:
    driver: bridge

volumes:
  wordpress:
  db:
